---
title: "AD_ladder_fragments"
output: html_document
date: "2025-10-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 
```{r}
# Add the function for ppm calculation
ppm = function(observed, theo){
 if(abs((observed - theo) / theo * 10^6) > 10) {
   return(FALSE)
 } else {
   return(TRUE)
 }
}

source("Source/introduction.R")
source("Source/blind_seq.R")
source("Source/plotting.R")

# get your dictionary file ready
dictionary = read_xlsx("Data/uni_dictionary.xlsx")
dictionary = dictionary[c(1, 2, 3, 4),]

set_up("mRNA", "ACACUCGGAUAUUUGAUAUGUGGAUUUCGAGUCGUCUUAAUGUAUAGAUUUGAAGAGGAGCUGUUUUUACGAUCCCUUCAGGAUU", "Data/Enzyme_AD/FlucmRNA_NIST_MazF1FA20min_T01_251023_SG_xiaohong_new.xlsx", "peptide", 330000, 0, 21)
```

```{r}
prophet_5 = prophet(df, theo_5) #this will be the data frame for matching result, name it whatever you want
prophet_3 = prophet(df, theo_3) #this will be the data frame for matching result, name it whatever you want

# first variable: your data frame
# second variable: your dictionary
#dictionary = dictionary[c(1, 2, 3, 4),]
algorithm_output = blind_seq(df, dictionary)

# first variable: the output data frame from nested algorithm
# second variable: the minimum length for ladders you want to include in your result file
# third variable: the location of your original data file
output_ladders_found(algorithm_output, 3,  file_location)

```

```{r adduct_finder}
assign("H2O", 18.01528, envir = .GlobalEnv)
assign("K", 39.0983, envir = .GlobalEnv)
assign("Na", 22.989769, envir = .GlobalEnv)
assign("H", 1.00784, envir = .GlobalEnv)
assign("Co", 57.9353, envir = .GlobalEnv)
assign("DIPA", 101.1204, envir = .GlobalEnv)
assign("P", 79.9, envir = .GlobalEnv)
assign("A", 329.05252, envir = .GlobalEnv)

theo_5_deH2O = theo_creater(df, theo_5, -H2O, "dehydrated 5'", 90, TRUE)
theo_5_H2O = theo_creater(df, theo_5, H2O, "hydrated 5'", 90, TRUE)
theo_5_Na = theo_creater(df, theo_5, Na-H, "Na adducted 5'", 90, TRUE)
theo_5_Co = theo_creater(df, theo_5, Co-H, "Co adducted 5'", 90, TRUE)
#theo_5_2Co = theo_creater(df, theo_5, (Co-H)*2, "2 Co adducted 5'", 90, TRUE)
theo_5_K = theo_creater(df, theo_5, K-H, "K adducted 5'", 90, TRUE)
#theo_5_DIPA = theo_creater(df, theo_5, DIPA, "DIPA adducted 5'", 90, TRUE)



# theo_3_Na = theo_creater(df, theo_3, Na-H, "Na adducted 3'", 90, FALSE)
# theo_3_Co = theo_creater(df, theo_3, Co-H, "Co adducted 3'", 90, FALSE)
# theo_3_2Co = theo_creater(df, theo_3, (Co-H)*2, "2 Co adducted 3'", 90, FALSE)
# #theo_3_K = theo_creater(df, theo_3, K-H, "K adducted 3'", 90, FALSE)
# #theo_3_DIPA = theo_creater(df, theo_3, DIPA, "DIPA adducted 3'", 90, FALSE)
# theo_3_P = theo_creater(df, theo_3, P, "P 3'", 90, FALSE)
# theo_3_PCo = theo_creater(df, theo_3, P+Co , "P Co adducted 3'", 90, TRUE)
# theo_3_A = theo_creater(df, theo_3, -A, "A loss 3'", 90, FALSE)
# theo_3_ACo = theo_creater(df, theo_3, Co-A, "A loss Co adducted 3'", 90, FALSE)
# theo_3_PCoH2O = theo_creater(df, theo_3, P+Co-H2O , "P Co adducted 3 dehy'", 90, TRUE)
# theo_3_PH2O = theo_creater(df, theo_3, P-H2O, "P dehy 3'", 90, TRUE)

new_theo_5 = theo_creater(df, theo_5, 0, "native 5'", 90, TRUE)
# new_theo_3 = theo_creater(df, theo_3, 0, "native 3'", 90, FALSE)

# write_xlsx(rbind(
#      new_theo_5, theo_5_deH2O, theo_5_Na, theo_5_Co, theo_5_H2O, theo_5_K), "Sec_May_all_layers.xlsx")#\theo_5_2Co, 
      #new_theo_3, theo_3_Co, theo_3_Na, theo_3_2Co,
      #theo_5_P, theo_5_PCo, theo_5_A, theo_5_ACo, theo_5_PCoH2O, theo_5_PH2O,
      #theo_3_P, theo_3_PCo, theo_3_A, theo_3_ACo, theo_3_PCoH2O, theo_3_PH2O), "Sec_May_all_layers.xlsx")
```

```{r}
df <- rbind(new_theo_5, theo_5_deH2O, theo_5_Na, theo_5_Co, theo_5_H2O, theo_5_K)
unique_positions <- unique(df$position_5)
length(unique_positions)
```

```{r Figure2b_2D_trace_fMet_BS_pseu, fig.height = 6, fig.width = 10}
df_2b = df %>% 
  select(-theoretical_mass, -relative_abundance) %>%
  arrange(ladder_type, monoisotopic_mass) %>% 
  filter(ladder_type %in% c("native 5'","dehydrated 5'"))

# adjust your x and y axis here
xlim  <- c(500, 15000)   
ylim  <- c(0, 15)             
xticks <- seq(500, 15000, by = 1000)               
yticks <- pretty(ylim, n = 6)
# ----------------------------------------

# color scale here
cold_to_warm <- c("#2c7bb6", "#00a6ca", "#ffffbf", "#fdae61", "#d7191c")

# Draw the figure
ggplot(df_2b, aes(x = monoisotopic_mass, y = apex_rt)) +
  geom_path(aes(group = ladder_type), size = 0.6, alpha = 0.8) +
  geom_point(aes(color = log_intensity, shape = ifelse(ladder_type != "native 5'", "circle", "square")), size = 3, stroke = 0.2) +
  scale_shape_manual(
    name = "ladder type",
    values = c("circle" = 16,  
               "square" = 15)  
  ) +
  scale_color_gradientn(
    colours = cold_to_warm,
    name = "log intensity",
    guide = guide_colorbar(
      title.position = "top",
      title.hjust = 0.5,
      barwidth = unit(0.5, "cm"),
      barheight = unit(2, "cm")
    )
  ) +
  scale_x_continuous(limits = xlim, breaks = xticks, expand = c(0,0)) +
  scale_y_continuous(limits = ylim, breaks = yticks, expand = c(0,0)) +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),            # remove grid
    legend.position = c(0.1, 0.6),         # adjust legend position
    legend.title = element_text(size = 10, face = "bold"),
    legend.text = element_text(size = 9),
    axis.line = element_line(color = "black", linewidth = 0.4)
  ) +
  labs(
    x = "",
    y = ""
  )

```

```{r}
plot_depth(df, c(1, 108))
```
